# Generated by Django 2.1.3 on 2019-01-02 23:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('gpos_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gpos_long', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia_contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True)),
                ('imagen', models.FileField(upload_to='fotografias')),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='core.Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia_localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='fotografias')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia_tipo_contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True)),
                ('imagen', models.FileField(upload_to='fotografias')),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('gpos_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gpos_long', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='core.Provincia'),
        ),
        migrations.AddField(
            model_name='fotografia_tipo_contenido',
            name='tipo_contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias_tipos_contenidos', to='core.Tipo_contenido'),
        ),
        migrations.AddField(
            model_name='fotografia_localidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='tipo_contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.Tipo_contenido'),
        ),
    ]
