# Generated by Django 2.1.3 on 2018-12-17 22:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField()),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('web', models.URLField(verbose_name='Web')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia_contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField()),
                ('imagen', models.FileField(upload_to='fotografias')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia_localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='fotografias')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provincia'),
        ),
        migrations.AddField(
            model_name='fotografia_localidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Localidad'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='tipo_contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_contenido'),
        ),
    ]
