# Generated by Django 2.1.3 on 2019-01-06 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='tipo_render',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.Tipo_render'),
            preserve_default=False,
        ),
    ]
