# Generated by Django 2.1.3 on 2018-12-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.Localidad'),
        ),
        migrations.AlterField(
            model_name='fotografia_contenido',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='core.Contenido'),
        ),
        migrations.AlterField(
            model_name='fotografia_localidad',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='core.Localidad'),
        ),
    ]
