# Generated by Django 2.1.3 on 2019-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190106_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='estrellas',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
