# Generated by Django 2.1.3 on 2018-12-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181217_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='tipo_contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.Tipo_contenido'),
        ),
    ]
