# Generated by Django 2.1.3 on 2018-12-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181217_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='core.Provincia'),
        ),
    ]
