# Generated by Django 2.1.3 on 2019-01-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contenido_estrellas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
