# Generated by Django 2.1.3 on 2018-12-18 14:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181217_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='fotografia_contenido',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotografia_localidad',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
