# Generated by Django 2.1.3 on 2019-01-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190107_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtipo_contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tipo_contenido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.Tipo_contenido'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='subtipo_contenido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.Subtipo_contenido'),
        ),
    ]
