# Generated by Django 2.1.3 on 2018-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181218_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
