# Generated by Django 2.0.2 on 2019-01-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190107_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='tipo_render',
        ),
        migrations.AddField(
            model_name='tipo_contenido',
            name='tipo_render',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_contenidos', to='core.Tipo_render'),
            preserve_default=False,
        ),
    ]
