# Generated by Django 2.1.3 on 2018-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_provincia_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_contenido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
