# Generated by Django 2.1.3 on 2018-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tipo_contenido_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia_contenido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
