# Generated by Django 2.1.3 on 2018-12-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fotografia_contenido_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fotografia_contenido',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fotografia_localidad',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='localidad',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipo_contenido',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
