# Generated by Django 2.0.2 on 2018-12-29 18:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181219_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia_tipo_contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', tinymce.models.HTMLField(blank=True, null=True)),
                ('imagen', models.FileField(upload_to='fotografias')),
                ('mod_time', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias_tipos_contenidos', to='core.Tipo_contenido')),
            ],
        ),
    ]
